apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: goodfood-dev
data:
  PORT: "8091"
  LOG_LEVEL: "info"
  POSTGRES_USER: "analytics_user"
  POSTGRES_DB: "analytics_db"
  ORDER_SERVICE_URL: "http://order-service:80"
  FRANCHISE_SERVICE_URL: "http://franchise-service:80"
  CACHE_TTL_SECONDS: "60"
