# 1. PVC pour conserver les données de Postgres sur k3s
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pvc
  namespace: goodfood-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # Ajustez la taille selon vos besoins
---
# 2. Déploiement de PostgreSQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: goodfood-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          envFrom:
            # Récupère POSTGRES_USER et POSTGRES_DB
            - configMapRef:
                name: order-service-config
            # Récupère POSTGRES_PASSWORD
            - secretRef:
                name: order-service-secret
          volumeMounts:
            - name: order-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: order-db-data
          persistentVolumeClaim:
            claimName: order-db-pvc
---
# 3. Service Kubernetes pour permettre à order-service de trouver order-db
apiVersion: v1
kind: Service
metadata:
  name: order-db # Ce nom permet de la contacter via "host=order-db"
  namespace: goodfood-dev
spec:
  selector:
    app: order-db
  ports:
    - port: 5432
      targetPort: 5432
