apiVersion: v1
kind: Service
metadata:
  name: order-service # Doit correspondre au nom du service
  namespace: goodfood-dev # Même namespace que le deployment
spec:
  type: ClusterIP
  selector:
    app: order-service # Doit matcher le label 'app' défini dans le deployment.yaml
  ports:
    - protocol: TCP
      port: 80 # Port exposé au sein du cluster
      targetPort: 8082 # Port d'écoute du conteneur Docker
