apiVersion: v1
kind: Service
metadata:
  name: promo-service
  namespace: goodfood-dev
spec:
  type: ClusterIP
  selector:
    app: promo-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8092
