apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-service-config
  namespace: goodfood-dev
data:
  PORT: "8084"
  LOG_LEVEL: "info"
  MONGO_USER: "delivery_user"
  MONGO_INITDB_ROOT_USERNAME: "delivery_user"
  MONGO_INITDB_DATABASE: "delivery_db"
  ORDER_SERVICE_URL: "https://api.c-mbk.fr/api/orders"
